# Logistic Regression in SciKit Learn - Lab

## Introduction 

In this lab, you are going to fit a logistic regression model to a dataset concerning heart disease. Whether or not a patient has heart disease is indicated in the final column labeled 'target'. 1 is for positive for heart disease while 0 indicates no heart disease.

## Objectives
You will be able to:

* Implement logistic regression in sci-kit learn
* Form conclusions about the performance of a model


## Let's get started!

In [2]:
#Starter Code
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
#Starter Code
df = pd.read_csv('heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

## Define appropriate X and y
Recall the dataset is whether or not a patient has heart disease and is indicated in the final column labelled 'target'. With that, define appropriate X and y in order to model whether or not a patient has heart disease.

In [4]:
#Your code here 
X = df.target
y = pd.concat([df.loc[:,["age", "trestbps", "chol", "thalach", "oldpeak"]], 
               pd.get_dummies(df.loc[:,["sex", "cp", "fbs", "exang", "slope", "ca", "thal"]])],
              axis=1)

In [5]:
pd.get_dummies(
    df.loc[:,["sex", "cp", "fbs", "exang", "slope", "ca", "thal"]])

     sex  cp  fbs  exang  slope  ca  thal
0      1   3    1      0      0   0     1
1      1   2    0      0      0   0     2
2      0   1    0      0      2   0     2
3      1   1    0      0      2   0     2
4      0   0    0      1      2   0     2
5      1   0    0      0      1   0     1
6      0   1    0      0      1   0     2
7      1   1    0      0      2   0     3
8      1   2    1      0      2   0     3
9      1   2    0      0      2   0     2
10     1   0    0      0      2   0     2
11     0   2    0      0      2   0     2
12     1   1    0      0      2   0     2
13     1   3    0      1      1   0     2
14     0   3    1      0      2   0     2
15     0   2    0      0      1   0     2
16     0   2    0      0      2   0     2
17     0   3    0      0      0   0     2
18     1   0    0      0      2   0     2
19     0   3    0      0      2   2     2
20     1   0    0      0      1   0     3
21     1   2    0      1      2   0     2
22     1   0    0      0      2   0     2
23     1   2    1      1      1   0     2
24     1   3    0      1      2   0     3
25     0   1    0      0      2   2     2
26     1   2    1      0      2   0     2
27     1   2    0      0      2   0     2
28     0   2    1      0      2   1     2
29     1   2    1      0      0   0     2
..   ...  ..  ...    ...    ...  ..   ...
273    1   0    0      0      2   1     3
274    1   0    0      1      1   1     2
275    1   0    0      0      2   2     3
276    1   0    0      0      1   1     3
277    1   1    0      0      2   0     3
278    0   1    1      0      2   2     2
279    1   0    0      1      1   1     2
280    1   0    0      1      1   0     1
281    1   0    1      1      1   0     0
282    1   2    1      0      1   1     1
283    1   0    0      0      2   0     3
284    1   0    0      1      2   1     3
285    1   0    0      1      1   2     3
286    1   3    0      0      2   2     2
287    1   1    0      0      2   1     2
288    1   0    0      1      1   1     3
289    0   0    0      1      1   1     3
290    1   0    0      0      2   1     3
291    1   0    0      0      0   3     1
292    0   0    1      1      1   2     1
293    1   2    0      0      1   0     3
294    1   0    0      1      0   0     1
295    1   0    0      1      2   2     3
296    0   0    0      1      1   0     2
297    1   0    1      0      1   2     1
298    0   0    0      1      1   0     3
299    1   3    0      0      1   0     3
300    1   0    1      0      1   2     3
301    1   0    0      1      1   1     3
302    0   1    0      0      1   1     2

[303 rows x 7 columns]

## Normalize the Data
Normalize the data prior to fitting the model.

In [ ]:
#Your code here

## Train Test Split
Split the data into train and test sets.

In [ ]:
#Your code here

## Fit a model
Fit an initial model to the training set. In sci-kit learn you do this by first creating an instance of the regression class. From there, then use the fit method from your class instance to fit a model to the training data.

In [ ]:
logreg = LogisticRegression(fit_intercept = False, C = 1e12) #Starter code
#Your code here

## Predict
Generate predictions for the train and test sets. Use the **predict** method from the logreg object.

In [ ]:
#Your code here

## Initial Evaluation
How many times was the classifier correct for the training set?

In [ ]:
#Your code here

## How many times was the classifier correct for the test set?

In [ ]:
#Your code here

## Analysis
Describe how well you think this initial model is performing based on the train and test performance. Within your description, make note of how you evaluated performance as compared to your previous work with regression.

In [ ]:
#Your answer here

## Summary

In this lab, you practiced a standard data science pipeline: importing data, splitting into train and test sets, and fitting a logistic regression model. In the upcoming labs and lessons, you'll continue to investigate how to analyze and tune these models for various scenarios.